<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <InvariantGlobalization>true</InvariantGlobalization>
  	<PublishDir>publish</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRPC" Version="1.0.0" />
    <PackageReference Include="SmashFramework" Version="1.2.2" />
  </ItemGroup>

  <ItemGroup>
      <Content Include="Assets\**\*">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
  </ItemGroup>

</Project>
