public enum TextInputOperation
{
    IncreasePointSize,
    DecreasePointSize,
    ToggleFileDialog,
    JumpUp,
    JumpLeft,
    JumpRight,
    JumpDown,
    DeleteWord,
    DeleteCharacter,
    NewLine,
    ForceNewLine,
    Tab,
    MoveRight,
    MoveLeft,
    SaveFile,
    PasteClipboard,
}