public enum TextAction
{
    None,
    DeleteCharacter,
    DeleteWord,
    MoveLeft,
    MoveRight,
    JumpLeft,
    JumpRight,
    MoveUp,
    MoveDown,
    InsertNewline,
    InsertTab,
    GoToEndOfLine,
    GoToStartOfLine,
    DeleteCharacterForward,
    DeleteWordForward,
    Paste,
}
